### ISSUE TITLE
does this flamegraph show anything interesting that can be optimized?

### ISSUE THREAD

**Issue by mrhooray** [benoitc/hackney#271]
Hi,

I'm new to elixir/erlang and here's a cpu [flamegrah](https://dl.dropboxusercontent.com/u/6255364/eflame.svg) of simple api server talking to downstream via hackney. Do you see anything within hackney can be further optimized?

Thanks

**Comment by benoitc** [comment]
What are the units? Not sure I totally understand that graph but as far I can see these improvements could be done:

- use [erlang-idna-nif](https://github.com/benoitc/erlang-idna-nif) instead of the pure erlang decoder/encoder [erlang-idna](https://github.com/benoitc/erlang-idna) . It will be a lot faster but should probably be an option or a way should be provided to have it running in platforms where it can't be built (or find a way to run nifs in erlangonxen or unikernels like this)
- use an HTTP parser in C like [erlhttp](https://github.com/mme/erlhttp)
- #276 will also improve a lot the performance by reducing the time to retrieve a connection

Hopefully I answered to your question. Any help is welcome anyway :)

**Comment by benoitc** [comment]
@mrhooray did it answer to your question?

**Comment by mrhooray** [comment]
@benoitc yeah i didn't find any oblivious low hanging fruit from the flamegraph so posted it to see your observation. it is actually pretty fast just not as to the extend of some other stacks. on the other hand hackney/erlang otp does more and provides some niceties isn't it :)
