### ISSUE TITLE
idna 5.0.2 has minimum otp version 18

### ISSUE THREAD

**Issue by tverlaan** [benoitc/hackney#425]
idna 5.0.2 states that R18 is the minimum OTP version. Hackney however states in the README:
> Supported versions of Erlang are R16B03-1, 17.3.4 and above. It is reported to work with R14B04 and R15B03-1.

rebar3 is checking the minimum OTP version of all dependencies and stops compiling idna & hackney for anything <R18. This is preventing me from moving a project (travelping/exometer_influxdb#42) to rebar3 and using hex.pm as a source for packages. How should we go about solving this?

- Lower idna requirement? Remove it?
- State that hackney works with minimum OTP version 18?

Thanks

**Comment by benoitc** [comment]
should be fixed in 16c29440c6d407cd84ef2d06aeca6f54663fe3f0 . I didn't test idna 5.1.0 with version < 19 though, so let me know.

For your info the next major release will only handle Erlang >= 19, only  fixes will be backported. So it may be better to make sure your code is compatible with latest Erlang.

**Comment by tverlaan** [comment]
Thanks for fixing!
