### ISSUE TITLE
NO_PROXY env variable support?

### ISSUE THREAD

**Issue by squarism** [benoitc/hackney#539]
I see no issue or code that mentions the common (but perhaps at a different abstraction level) environment variables `no_proxy` and `NO_PROXY`.  These variables are probably in edge-case and annoying land but they allow for flexible security or are just plain expected.  Many http clients have these settings but woefully, are even less common than proxy options to begin with.  Hackney support proxies and that's been working fine.  In AWS, I find a need to have some requests route different depending on the DNS domain name for various reasons beyond my control.  I was wondering if this is even a possibility or is hackney more low level where _it is up to you_ to call connect_proxy or not and hackney wouldn't ever look for `NO_PROXY` or maybe anything in ENV at all.

**Comment by benoitc** [comment]
Hackney by default doesn't use a proxy until you set it to use one. This may change in the future but for now looking at this env is not needed.

**Comment by spapas** [comment]
Hello @benoitc the expected behavior (from various other http client libraries) is to actually take a peek at the well-known env variables (`http_proxy/HTTP_PROXY`, `https_proxy/HTTPS_PROXY` and `no_proxy/NO_PROXY`) and configure the client to actually use 'em if they are there. Take a look at the well-known and super-popular python requests library for example or the curl http client. 

Since these env vars are configured they are expected to be used automatically. So I would recommend to reconsider your decision and re-open this issue and also add the http_proxy and friends env vars. Of course the developer can actually check if the env vars are present and configure hackney to use the proxy, however this is extra work for the developer that wants to use hackney. Also notice that hackney is used by various *other* libraries internally making  it more difficult to properly configure it (since the other libraries would need to to allow hackney configuration through their API).

As a final remark I'd like to notice here that using a proxy should be considered *the normal* and not an outlier, at least in corporate environments. Very few environments allow their users unrestricted access to http resources without a proxy. So it is important to make proxy configuration as simple as possible and the env vars are right now the gold standard for configuring the proxy.

**Comment by gp42** [comment]
We are hitting this problem as well... Especially when hackney is used by third-party libraries. Is there any chance to reconsider and actually implement ENV Var support? This is definitely a standard.

**Comment by Coffei** [comment]
@benoitc Shouldn't this be revisited since proxy ENV variables are now supported? It seems incomplete to support `HTTP(S)_PROXY` and not `NO_PROXY`.
