### ISSUE TITLE
Pool explanation

### ISSUE THREAD

**Issue by 9mm** [benoitc/hackney#547]
Hey, can you explain a bit more in detail how the pool works?

Does it automatically open connections to match `max_connections` or does it organically open them when you make a request, and then lets them close if there is no request or response sent through the connection within the `timeout` value? Or does it do something else?

I'm trying to achieve 100's of thousands of outgoing requests on a 64 vCPU server and I'm trying to figure out how to tune these settings.

Also I'm confused by these other github issues that say hackney doesnt reuse the same pool item and people are wanting to use poolboy, can you explain what the benefit of that is?

**Comment by Hinidu** [comment]
hackney's pool doesn't and can't automatically open connections to match `max_connections` because connection can be opened to any host. So AFAIK it just puts opened by your requests connections when they become free in the pool until they will be closed by any way.

And I don't think that hackney's pool is suited for highload because it uses a queue of waiting processes and filters them using `O(n)` time and memory when waiting process is crashing, etc. And the pool's message queue starts to grow indefinitely because of that. Sadly I had no time yet to think how it can be made faster but I hope I will have some time soon - otherwise I think the only way for me will be to disable the pool for now.

**Comment by benoitc** [comment]
@Hinidu it all depends on how you're using the pool :) You can setup as many pool as many hosts you have, which is how you can actually scale it.  Feel free to ping me if you want more detail about it

Anyway, the current design of the pool is to limit the number of live connections using a pool. Since the number of connections to an host is supposed to be small (to prevent any network congestion) using a list to maintain the running process  is not really an issue. Note that you can detach a connection from the pool for long running connections. This design has been enough sucessfull to be used in a some large services.

There is a new design in progress to improve the pool and remove the need of using external dependencies, but progress have been slow yet since the work is not sponsored yet.

**Comment by Hinidu** [comment]
Btw I found a few minutes to think about this problem and I think it will be quite simple to defer the removal from this pending queue by storing pid in a hashtable and checking this hashtable after dequeueing the next pending process and skipping it if this process were "removed" from the queue. I hope I will find a few more minutes to implement and test this approach today or tomorrow.

**Comment by Hinidu** [comment]
I've created another issue https://github.com/benoitc/hackney/issues/549 to track my progress and stop spamming this issue with not very much related comments :slightly_smiling_face:

**Comment by 9mm** [comment]
Wow thats awesome @Hinidu thanks for the comments guys

**Comment by benoitc** [comment]
I just released 1.15.0 to include 74159da340a03f3a3a0cc944814ff4338ab07ce6 . Should have been done a long time ago.  cc @Hinidu @9mm

**Comment by 9mm** [comment]
awesome! thank you :D

**Comment by benoitc** [comment]
closing the issue as answered. Feel free to open  new one or participate to #549 for further enhancements :)
