### ISSUE TITLE
TLS support may be broken on OTP 20.0 / 20.1

### ISSUE THREAD

**Issue by g-andrade** [benoitc/hackney#636]
As per @okeuday's [comment](https://github.com/benoitc/hackney/commit/533889df19eb51d4600f383bbeaad17bc6bc4fe7#r39625597) on `hackney_ssl.erl`, which correlates with a few errors I saw when running the test suites on multiple OTP versions a few days ago but didn't have the chance to investigate.

Creating this issue mostly as a reminder to fix this issue since I'm the one to blame[*], but also for transparency in case anyone else bumps into the same problem.

[*]: *mea culpa, mea culpa, mea maxima culpa*

**Comment by g-andrade** [comment]
Closed by #637 .

**Comment by okeuday** [comment]
@g-andrade You probably want to use versions from the list https://docs.travis-ci.com/user/languages/erlang/#otprelease-versions for #639 because the Erlang/OTP team has been moving away from release tarballs and using git tags instead (so the "stable" or latest version becomes more of a moving target).
